### PR TITLE
Create login module

### PR DESCRIPTION
**Pull request by qdequippe**
Hi,

This PR adds a login module to blur-admin and injects automatically js files in auth.html.

### CODE REVIEW

**Comment by Cu4rach4** [comment]
@akveo-private could you accept this pull?

**Comment by Cu4rach4** [comment]
@qdequippe how you add this after dashboard, when i change all modified files and then adding app.js the app frozen!...could you help me!

**Comment by qdequippe** [comment]
Hi @Cu4rach4 what did you mean by the app frozen, do you have some logs? and why did you add app.js, did you add the module `BlurAdmin.login`?

**Comment by Cu4rach4** [comment]
hi @qdequippe, the app is frozen on $pageFinishedLoading, gulp doent log me any error, so i can't solve the problem!

sorry for my english...a lot of time since my last writte or spoke.

**Comment by allanpoppe** [comment]
@qdequippe after modifying the 5 files, I'm getting an error in auth.html:

`jquery.js:3869 Uncaught Error: [$injector:modulerr] Failed to instantiate module BlurAdmin.login due to:
Error: [$injector:nomod] Module 'BlurAdmin.login' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

It seens like the module is not being injected. There is nothing being injected in the `<!-- build:js({.tmp/serve,.tmp/partials,src}) scripts/app.js -->` part of auth.html.

Any ideas?

**Comment by allanpoppe** [comment]
Another issue with this approach is that we can't use a factory or even $rootScope to store user data, because we need a redirect with $window.location.href inside login function to go to the index.html.
How do you store user data? Local storage?

**Comment by qdequippe** [comment]
Sorry I don't have time to test it again, I will try to check that this week

**Comment by dodomui** [comment]
I am having the same error as per pasted below.
(Also I am very new to AngularJs and first saw gulp generate project. The structure seem quite different than what I learn from AngularJS.org)
Appreciate if anyone can help to eliminate what should I do.

Uncaught Error: [$injector:modulerr] Failed to instantiate module BlurAdmin.login due to:
Error: [$injector:nomod] Module 'BlurAdmin.login' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.11/$injector/nomod?p0=BlurAdmin.login
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at http://localhost:3000/bower_components/angular/angular.js:2133:17
    at ensure (http://localhost:3000/bower_components/angular/angular.js:2057:38)
    at module (http://localhost:3000/bower_components/angular/angular.js:2131:14)
    at http://localhost:3000/bower_components/angular/angular.js:4669:22
    at forEach (http://localhost:3000/bower_components/angular/angular.js:325:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4653:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4575:19)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1809:20)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1830:12)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=BlurAdmin.login&p1…F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A1830%3A12)
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at http://localhost:3000/bower_components/angular/angular.js:2133:17
    at ensure (http://localhost:3000/bower_components/angular/angular.js:2057:38)
    at module (http://localhost:3000/bower_components/angular/angular.js:2131:14)
    at http://localhost:3000/bower_components/angular/angular.js:4669:22
    at forEach (http://localhost:3000/bower_components/angular/angular.js:325:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4653:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4575:19)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1809:20)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1830:12)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=BlurAdmin.login&p1…F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A1830%3A12)
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at http://localhost:3000/bower_components/angular/angular.js:4692:15
    at forEach (http://localhost:3000/bower_components/angular/angular.js:325:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4653:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4575:19)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1809:20)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1830:12)
    at angularInit (http://localhost:3000/bower_components/angular/angular.js:1715:5)
    at HTMLDocument.<anonymous> (http://localhost:3000/bower_components/angular/angular.js:32616:5)
    at mightThrow (http://localhost:3000/bower_components/jquery/dist/jquery.js:3570:29)

**Comment by dodomui** [comment]
@allanpoppe I solved it already.
Found is because gulp/inject.js got inject the injectAuth previously.
After remove it then is work already.

gulp.task('inject', ['scripts', 'styles', 'inject404', 'copyVendorImages'], function () {

**Comment by devDhrey** [comment]
@qdequippe @allanpoppe how do i make this new login module......my initial page, the admin have to log in to before getting access to the dashboard

**Pull request closed without merging**
